# create_collection { #databpy.create_collection }

```python
create_collection(name='NewCollection', parent=None)
```

Create a new Blender collection or retrieve an existing one.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type                                                         | Description                                                                                                                                                                                                                       | Default           |
|--------|--------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|
| name   | [str](`str`)                                                 | The name of the collection to create or retrieve. Default is "NewCollection".                                                                                                                                                     | `'NewCollection'` |
| parent | [Collection](`bpy.types.Collection`) or [str](`str`) or None | The parent collection to link the new collection to. If a string is provided, it will be used to find an existing collection by name. If None, the new collection will be linked to the scene's root collection. Default is None. | `None`            |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                                 | Description                                  |
|--------|--------------------------------------|----------------------------------------------|
|        | [Collection](`bpy.types.Collection`) | The created or retrieved Blender collection. |

## Raises {.doc-section .doc-section-raises}

| Name   | Type                     | Description                                                                    |
|--------|--------------------------|--------------------------------------------------------------------------------|
|        | [TypeError](`TypeError`) | If the parent parameter is not a Collection, string or None.                   |
|        | [KeyError](`KeyError`)   | If the parent collection name provided does not exist in bpy.data.collections. |