# create_object { #databpy.create_object }

```python
create_object(
    vertices=None,
    edges=None,
    faces=None,
    name='NewObject',
    collection=None,
)
```

Create a new Blender object and corresponding mesh.

Vertices are created for each row in the vertices array. If edges and / or faces are created then they are also
initialized but default to None.

## Parameters {.doc-section .doc-section-parameters}

| Name       | Type                 | Description                                                      | Default       |
|------------|----------------------|------------------------------------------------------------------|---------------|
| vertices   | np.ndarray           | The vertices of the vertices as a numpy array. Defaults to None. | `None`        |
| edges      | np.ndarray           | The edges of the object as a numpy array. Defaults to None.      | `None`        |
| faces      | np.ndarray           | The faces of the object as a numpy array. Defaults to None.      | `None`        |
| name       | str                  | The name of the object. Defaults to 'NewObject'.                 | `'NewObject'` |
| collection | bpy.types.Collection | The collection to link the object to. Defaults to None.          | `None`        |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description         |
|--------|--------|---------------------|
|        | Object | The created object. |