# Function reference {.doc .doc-index}

## Attribute

For interacting with attributes on meshes

| | |
| --- | --- |
| [named_attribute](named_attribute.qmd#databpy.named_attribute) | Get the named attribute data from the object. |
| [store_named_attribute](store_named_attribute.qmd#databpy.store_named_attribute) | Adds and sets the values of an attribute on the object. |
| [remove_named_attribute](remove_named_attribute.qmd#databpy.remove_named_attribute) | Remove a named attribute from an object. |
| [AttributeDomains](AttributeDomains.qmd#databpy.AttributeDomains) | Enumeration of attribute domains in Blender. You can store an attribute onto one of |
| [AttributeTypes](AttributeTypes.qmd#databpy.AttributeTypes) | Enumeration of attribute types in Blender. |
| [AttributeArray](AttributeArray.qmd#databpy.AttributeArray) | A numpy array subclass that automatically syncs changes back to the Blender object. |

## Collections

Working with collections in Blender

| | |
| --- | --- |
| [create_collection](create_collection.qmd#databpy.create_collection) | Create a new Blender collection or retrieve an existing one. |

## Objects

| | |
| --- | --- |
| [create_object](create_object.qmd#databpy.create_object) | Create a new Blender object and corresponding mesh. |
| [create_bob](create_bob.qmd#databpy.create_bob) | Create a BlenderObject wrapper around a new Blender object. |
| [evaluate_object](evaluate_object.qmd#databpy.evaluate_object) | Return an object which has the modifiers evaluated. |
| [BlenderObject](BlenderObject.qmd#databpy.BlenderObject) | A convenience class for working with Blender objects |
| [LinkedObjectError](LinkedObjectError.qmd#databpy.LinkedObjectError) | Error raised when a Python object doesn't have a linked object in the 3D scene. |