# store_named_attribute { #databpy.store_named_attribute }

```python
store_named_attribute(
    obj,
    data,
    name,
    atype=None,
    domain=AttributeDomains.POINT,
    overwrite=True,
)
```

Adds and sets the values of an attribute on the object.

## Parameters {.doc-section .doc-section-parameters}

| Name      | Type                          | Description                                                                   | Default                  |
|-----------|-------------------------------|-------------------------------------------------------------------------------|--------------------------|
| obj       | bpy.types.Object              | The Blender object.                                                           | _required_               |
| data      | np.ndarray                    | The attribute data as a numpy array.                                          | _required_               |
| name      | str                           | The name of the attribute.                                                    | _required_               |
| atype     | str or AttributeTypes or None | The attribute type to store the data as. If None, type is inferred from data. | `None`                   |
| domain    | str or AttributeDomains       | The domain of the attribute, by default 'POINT'.                              | `AttributeDomains.POINT` |
| overwrite | bool                          | Whether to overwrite existing attribute, by default True.                     | `True`                   |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                | Description                      |
|--------|---------------------|----------------------------------|
|        | bpy.types.Attribute | The added or modified attribute. |

## Raises {.doc-section .doc-section-raises}

| Name   | Type                   | Description                                    |
|--------|------------------------|------------------------------------------------|
|        | ValueError             | If atype string doesn't match available types. |
|        | AttributeMismatchError | If data length doesn't match domain size.      |

## Examples {.doc-section .doc-section-examples}

```{python}
import bpy
import numpy as np
from databpy import store_named_attribute, list_attributes, named_attribute
obj = bpy.data.objects["Cube"]
print(f"{list_attributes(obj)=}")
```
```{python}
store_named_attribute(obj, np.arange(8), "test_attribute")
print(f"{list_attributes(obj)=}")
```
```{python}
named_attribute(obj, "test_attribute")
```