name: docs-build-deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      BLENDER_VERSION: blender-4.2.0-linux-x64
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v5
        with:
            python-version: "3.11.7"
            cache: pip
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
            version: "latest"

      - name: Build Docs
        run: |
            uv sync --all-extras --dev
            cd docs
            uv pip install -e .
            uv run -m quartodoc build

      - name: Quarto Render
        run: |
            uv run quarto render docs

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
            target: gh-pages
            path: docs
            render: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
