name: Lint & Type Check

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]


jobs:
    lint:
      name: Check code style
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Check code formatting
        run: uv run ruff format --diff
      - name: Lint code base
        run: uv run ruff check

    typecheck:
      name: Type check with ty
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Type check
        run: uv run ty check
