name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ['4.5', '5.0', '5.1']
              os: [macos-latest, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v4

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "latest"

            - name: Install Intel oneAPI Runtime
              if: matrix.os == 'ubuntu-latest' && matrix.version != '4.5'
              run: |
                wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
                echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
                sudo apt-get update
                sudo apt-get install -y intel-oneapi-runtime-libs
              
            - name: Install
              run: |
                uv sync  --all-extras --dev
                uv pip install "bpy==${{ matrix.version }}.*" --extra-index-url https://bradyajohnston.github.io/dailybpy/ --index-strategy unsafe-best-match  --prerelease=allow
            
            - name: Run tests
              run: |
                uv run -m pytest -vv --cov=databpy --cov-report=xml
    
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              if: matrix.os == 'macos-latest' && matrix.version == '5.0'
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                name: coverage.xml

            - name: Upload coverage reports to Codecov
              if: matrix.os == 'macos-latest' && matrix.version == '5.0'
              uses: codecov/codecov-action@v3
    
