name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["4.2", "4.3"]
              os: [macos-14]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.11.7
                cache: pip

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "latest"
            
            - name: Install
              run: |
                uv venv --python=3.11
                source .venv/bin/activate
                uv pip install -r pyproject.toml --all-extras
                uv pip install -e .
                uv pip install bpy==${{ matrix.version }}
            
            - name: Run tests
              run: |
                source .venv/bin/activate
                pytest -vv --cov=databpy --cov-report=xml
    
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              if: matrix.os == 'macos-14' && matrix.version == '4.2'
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                name: coverage.xml

            - name: Upload coverage reports to Codecov
              if: matrix.os == 'maxos-14' && matrix.version == '4.2'
              uses: codecov/codecov-action@v3
    
