name: Run Tests in Blender

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["4.2.5", "4.3.2", "daily"]
              os: [macos-14]
        steps:
            - uses: actions/checkout@v4
            - uses: BradyAJohnston/setup-blender@v2.1
              with:
                version: ${{ matrix.version }}
            - name: Install and Test
              run: |
                blender -b -P tests/python.py -- -m pip install -e ".[test]"
                blender -b -P tests/run.py -- -vv
