name: Test Upstream

on: 
    pull_request:
      branches: ["main"]
    
jobs:
    test-in-blender:
        runs-on: ${{ matrix.os }}
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
            REPO_NAME: "BradyAJohnston/databpy"
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["latest"]
              os: [ubuntu-latest]
              repo: ["BradyAJohnston/MolecularNodes", "kolibril13/blender_csv_import"]
        steps:
            - uses: actions/checkout@v5
              with:
                repository: ${{ matrix.repo }}
            
            - uses: BradyAJohnston/setup-blender@v5
              with: 
                version: ${{ matrix.version }}
            
            - name: Install and Test
              run: |
                blender -b -P tests/python.py -- -m pip install -e ".[test]"
                blender -b -P tests/python.py -- -m pip install git+https://github.com/${{ env.REPO_NAME}}.git@${{ env.BRANCH_NAME }}
                blender -b -P tests/run.py -- -vv