name: Run Tests in Blender

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["4.2", "4.3"]
              os: [macos-14, ubuntu-latest, windows-latest]
              repo: ["BradyAJohnston/MolecularNodes"]
        steps:
            - uses: actions/checkout@v4
              with:
                repository: ${{ matrix.repo }}
            
            - uses: BradyAJohnston/setup-blender@v3
              with: 
                version: ${{ matrix.version }}
            
            - name: Install and Test
              run: |
                blender -b -P tests/python.py -- -m pip install -e ".[test]"
                blender -b -P tests/python.py -- -m pip install git+https://github.com/BradyAJohnston/databpy.git@${{ env.BRANCH_NAME }}
                blender -b -P tests/run.py -- -vv